### ISSUE TITLE
Compatible with Vitis 2020.2

### ISSUE THREAD

**Issue by KerstinKeller** [Xilinx/cmakeModules#1]
Hi,

sorry if this is a dumb question, but will these Scripts be working with Vitis 2020.2? The commits are about 2 years old.
I am just getting up to speed working with the tools, but as I am very used to having CMake for all other C++ projects.

I'd prefer setting up projects with CMake, and then opt-in on Simulation and Hardware synthesis. Is this even possible?
Is there any documentation?
I feel that a CMake approach will be the only reasonable one, when integrating with more complex projects.

Sorry again for what seems like a beginner question.

**Comment by HPC-Ken** [comment]
Hi,
Thanks for you question
These scripts were part of an inhouse labs project on how best to support the tools with CMake. For recent production examples I would suggest looking at the Vitis examples "https://github.com/Xilinx/Vitis_Accel_Examples/tree/master/host". In each example there is a cmake_build folder which could be used as a template for your work. 
The current best practices, if using CMake, is to build the hardware/simulation (xclbin related actions) with standard make and the host compilation only with CMake.

**Comment by denolf** [comment]
update for 2021.2 complete
