### ISSUE TITLE
FindLibXAIE has hard coded paths

### ISSUE THREAD

**Issue by fifield** [Xilinx/cmakeModules#3]
It should support LibXAIE_DIR and/or LibXAIE_ROOT.

**Comment by fifield** [comment]
I was able to use [branch2021.2](https://github.com/Xilinx/cmakeModules/tree/branch2021_2) and the `XAIENGINE_LOCAL_DIR` environment variable as a workaround.

**Comment by jackl-xilinx** [comment]
Agreed. Thanks for the feedback and improvement. I will fix this on the next push to the branch (and eventual push to main)

**Comment by fifield** [comment]
Fixed in https://github.com/Xilinx/cmakeModules/pull/4
